config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/home/uf_value', to: 'home#uf_value'
  get '/home/dolar_value', to: 'home#dolar_value'

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def uf_value
    api_url = "https://mindicador.cl/api/uf/#{(@date_today)}"
    response = HTTParty.get(api_url)
    responsetohash = JSON.parse(response.read_body)
    if responsetohash['serie'][0].nil?
      return render json: {mensaje:"Valor no existe en esa fecha"}
    else 
      @uf_value = responsetohash['serie'][0]['valor']
    end
  end

  def dolar_value
    api_url = "https://mindicador.cl/api/dolar/#{(@date_today)}"
    response = HTTParty.get(api_url)
    responsetohash = JSON.parse(response.read_body)
    if responsetohash['serie'][0].nil?
      return render json: {mensaje:"Valor no existe en esa fecha"}
    else 
      @dolar_value = responsetohash['serie'][0]['valor']
    end
  end

  def date_today
    @date_today = Time.now.strftime("%m-%d-%Y")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/dolar_value.html.erb
<%= turbo_frame_tag "dolar_value" do %>
    <p><%= number_to_currency(@dolar_value) %> CLP</p>
<% end %>

app/views/home/index.html.erb
<%= turbo_frame_tag "uf_value" do %>
    <%= link_to "Valor UF", home_uf_value_path %>
<% end %>
<%= turbo_frame_tag "dolar_value" do %>
    <%= link_to "Valor Dolar", home_dolar_value_path %>
<% end %>

app/views/home/uf_value.html.erb
<%= turbo_frame_tag "uf_value" do %>
	<p><%= number_to_currency(@uf_value) %> CLP</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UfApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>